-- ==============================================================================
-- SUPABASE DATABASE & STORAGE SCHEMA FOR ABIR MAHMUD PORTFOLIO
-- ==============================================================================

-- 1. Enable UUID Extension (if needed)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT NOT NULL,
  tech_stack JSONB NOT NULL DEFAULT '[]'::jsonb,
  thumb JSONB NOT NULL DEFAULT '{}'::jsonb,
  image_gallery JSONB NOT NULL DEFAULT '[]'::jsonb,
  live_url JSONB NOT NULL DEFAULT '[]'::jsonb,
  github_url JSONB NOT NULL DEFAULT '[]'::jsonb,
  case_study_url JSONB NOT NULL DEFAULT '[]'::jsonb,
  featured BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. Create Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_projects_slug ON public.projects(slug);
CREATE INDEX IF NOT EXISTS idx_projects_featured ON public.projects(featured);
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON public.projects(created_at DESC);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- 5. Define Projects RLS Policies
-- Allow anyone (public) to view/read projects
DROP POLICY IF EXISTS "Public can view projects" ON public.projects;
CREATE POLICY "Public can view projects"
  ON public.projects
  FOR SELECT
  TO public
  USING (true);

-- Allow authenticated users (admin dashboard) full CRUD permissions
DROP POLICY IF EXISTS "Authenticated users can insert projects" ON public.projects;
CREATE POLICY "Authenticated users can insert projects"
  ON public.projects
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can update projects" ON public.projects;
CREATE POLICY "Authenticated users can update projects"
  ON public.projects
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can delete projects" ON public.projects;
CREATE POLICY "Authenticated users can delete projects"
  ON public.projects
  FOR DELETE
  TO authenticated
  USING (true);

-- ==============================================================================
-- 6. Supabase Storage Bucket Setup: 'projects'
-- ==============================================================================

-- Create 'projects' public storage bucket
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'projects',
  'projects',
  true,
  10485760, -- 10MB limit per file
  ARRAY['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/svg+xml', 'image/gif']
)
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 10485760;

-- Storage RLS Policies
DROP POLICY IF EXISTS "Public can view project bucket files" ON storage.objects;
CREATE POLICY "Public can view project bucket files"
  ON storage.objects
  FOR SELECT
  TO public
  USING (bucket_id = 'projects');

DROP POLICY IF EXISTS "Authenticated users can upload to project bucket" ON storage.objects;
DROP POLICY IF EXISTS "Allow uploads to project bucket" ON storage.objects;
CREATE POLICY "Allow uploads to project bucket"
  ON storage.objects
  FOR INSERT
  TO public
  WITH CHECK (bucket_id = 'projects');

DROP POLICY IF EXISTS "Authenticated users can update project bucket files" ON storage.objects;
DROP POLICY IF EXISTS "Allow updates to project bucket files" ON storage.objects;
CREATE POLICY "Allow updates to project bucket files"
  ON storage.objects
  FOR UPDATE
  TO public
  USING (bucket_id = 'projects')
  WITH CHECK (bucket_id = 'projects');

DROP POLICY IF EXISTS "Authenticated users can delete project bucket files" ON storage.objects;
DROP POLICY IF EXISTS "Allow delete from project bucket" ON storage.objects;
CREATE POLICY "Allow delete from project bucket"
  ON storage.objects
  FOR DELETE
  TO public
  USING (bucket_id = 'projects');

-- ==============================================================================
-- 7. Seed Initial Projects Data
-- ==============================================================================

INSERT INTO public.projects (
  title,
  slug,
  description,
  tech_stack,
  thumb,
  image_gallery,
  live_url,
  github_url,
  case_study_url,
  featured
)
VALUES
(
  'SkillOxygen',
  'skill-oxygen',
  'SkillOxygen is an interview platform where experienced professionals can conduct mock interviews for fresh graduates and job seekers. It includes features like interview scheduling, online payments, feedback collection, secure dashboards, and a monetization system.',
  '["nextjs", "tailwindcss", "shadcn", "typescript", "nodejs", "express", "mongodb", "postgresql", "prisma"]'::jsonb,
  '{"id": 1, "url": "/images/projects/project-placeholder.svg", "title": "SkillOxygen dashboard"}'::jsonb,
  '[
    {"id": 1, "url": "/images/projects/project-placeholder.svg", "title": "Interview scheduling dashboard"},
    {"id": 2, "url": "/images/projects/project-placeholder.svg", "title": "Mock interview room"},
    {"id": 3, "url": "/images/projects/project-placeholder.svg", "title": "Payments & feedback view"}
  ]'::jsonb,
  '[{"id": 1, "name": "skilloxgen.com", "url": "https://skilloxgen.com"}]'::jsonb,
  '[{"id": 1, "title": "SkillOxygen", "url": "https://github.com/skilloxgen"}]'::jsonb,
  '[{"id": 1, "title": "SkillOxygen Case Study", "url": "https://github.com/skilloxgen"}]'::jsonb,
  true
),
(
  'E-Commerce Management System',
  'ecommerce-management-system',
  'A complete e-commerce platform with inventory management and accounting features, including product management, sales, customer management, dashboards, and reports.',
  '["react", "nodejs", "express", "mongodb", "postgresql", "prisma", "typescript"]'::jsonb,
  '{"id": 2, "url": "/images/projects/project-placeholder.svg", "title": "E-Commerce admin dashboard"}'::jsonb,
  '[
    {"id": 1, "url": "/images/projects/project-placeholder.svg", "title": "Inventory management dashboard"},
    {"id": 2, "url": "/images/projects/project-placeholder.svg", "title": "Sales & accounting reports"},
    {"id": 3, "url": "/images/projects/project-placeholder.svg", "title": "Customer management view"}
  ]'::jsonb,
  '[{"id": 1, "name": "Live Demo", "url": "#"}]'::jsonb,
  '[{"id": 1, "title": "Source Code", "url": "#"}]'::jsonb,
  '[]'::jsonb,
  true
),
(
  'Fingerprint Authentication API',
  'fingerprint-authentication-api',
  'A backend authentication system integrating Futronic fingerprint devices with FastAPI. Provides biometric verification, SDK integration, secure APIs, and template matching.',
  '["fastApi", "typescript"]'::jsonb,
  '{"id": 3, "url": "/images/projects/project-placeholder.svg", "title": "Fingerprint API architecture"}'::jsonb,
  '[
    {"id": 1, "url": "/images/projects/project-placeholder.svg", "title": "API documentation"},
    {"id": 2, "url": "/images/projects/project-placeholder.svg", "title": "Device enrollment flow"},
    {"id": 3, "url": "/images/projects/project-placeholder.svg", "title": "Template matching results"}
  ]'::jsonb,
  '[]'::jsonb,
  '[{"id": 1, "title": "Source Code", "url": "#"}]'::jsonb,
  '[{"id": 1, "title": "Case Study", "url": "#"}]'::jsonb,
  true
),
(
  'Portfolio Website',
  'portfolio-website',
  'A personal portfolio site built with Next.js and Tailwind CSS, featuring animated sections, dark mode, and a fully responsive layout to showcase projects and experience.',
  '["nextjs", "tailwindcss", "typescript"]'::jsonb,
  '{"id": 4, "url": "/images/projects/project-placeholder.svg", "title": "Portfolio homepage"}'::jsonb,
  '[
    {"id": 1, "url": "/images/projects/project-placeholder.svg", "title": "Hero section"},
    {"id": 2, "url": "/images/projects/project-placeholder.svg", "title": "Projects section"},
    {"id": 3, "url": "/images/projects/project-placeholder.svg", "title": "Dark mode view"}
  ]'::jsonb,
  '[{"id": 1, "name": "Live Demo", "url": "#"}]'::jsonb,
  '[{"id": 1, "title": "Source Code", "url": "#"}]'::jsonb,
  '[]'::jsonb,
  false
),
(
  'Task Management App',
  'task-management-app',
  'A collaborative task management application with boards, real-time updates, and team workspaces, built with React, Redux, and a Node.js/Express API.',
  '["react", "redux", "nodejs", "express", "mongodb", "typescript"]'::jsonb,
  '{"id": 5, "url": "/images/projects/project-placeholder.svg", "title": "Task board view"}'::jsonb,
  '[
    {"id": 1, "url": "/images/projects/project-placeholder.svg", "title": "Kanban board"},
    {"id": 2, "url": "/images/projects/project-placeholder.svg", "title": "Team workspace"},
    {"id": 3, "url": "/images/projects/project-placeholder.svg", "title": "Task detail modal"}
  ]'::jsonb,
  '[{"id": 1, "name": "Live Demo", "url": "#"}]'::jsonb,
  '[{"id": 1, "title": "Source Code", "url": "#"}]'::jsonb,
  '[{"id": 1, "title": "Case Study", "url": "#"}]'::jsonb,
  false
),
(
  'Blog CMS',
  'blog-cms',
  'A headless-style content management system for blogs with a markdown editor, tag-based filtering, and an admin panel, powered by Next.js, Prisma, and PostgreSQL.',
  '["nextjs", "prisma", "postgresql", "tailwindcss", "typescript", "react-query"]'::jsonb,
  '{"id": 6, "url": "/images/projects/project-placeholder.svg", "title": "Blog CMS admin panel"}'::jsonb,
  '[
    {"id": 1, "url": "/images/projects/project-placeholder.svg", "title": "Markdown editor"},
    {"id": 2, "url": "/images/projects/project-placeholder.svg", "title": "Post list & filters"},
    {"id": 3, "url": "/images/projects/project-placeholder.svg", "title": "Public blog view"}
  ]'::jsonb,
  '[{"id": 1, "name": "Live Demo", "url": "#"}]'::jsonb,
  '[{"id": 1, "title": "Source Code", "url": "#"}]'::jsonb,
  '[]'::jsonb,
  false
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  tech_stack = EXCLUDED.tech_stack,
  thumb = EXCLUDED.thumb,
  image_gallery = EXCLUDED.image_gallery,
  live_url = EXCLUDED.live_url,
  github_url = EXCLUDED.github_url,
  case_study_url = EXCLUDED.case_study_url,
  featured = EXCLUDED.featured,
  updated_at = timezone('utc'::text, now());
